### ISSUE TITLE
Lib fails to import organdata dataset

### ISSUE THREAD

**Issue by pedrotokar** [Gedevan-Aleksizde/pysocviz#1]
When I try to load the `organdata` dataset, I get an error saying that converting a field to datetime failed. 

**importing line:**
```py
from pysocviz.loader import load_dataset
organdata = load_dataset("organdata")
```

**error:**
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[working dir]/lib/python3.10/site-packages/pysocviz/loader/loader.py", line 51, in load_dataset
    return d.assign(**convert_funs)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/frame.py", line 4854, in assign
    data[k] = com.apply_if_callable(v, data)
  File "[working dir]/lib/python3.10/site-packages/pandas/core/common.py", line 379, in apply_if_callable
    return maybe_callable(obj, **kwargs)
  File "/[working dir]/lib/python3.10/site-packages/pysocviz/loader/loader.py", line 43, in <lambda>
    c: (lambda col: lambda x:  map_dtype_base[
  File "/[working dir]/lib/python3.10/site-packages/pysocviz/loader/loader.py", line 21, in <lambda>
    'Date': lambda x: x.astype('datetime64'),
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 116, in _astype_nansafe
    return dta.astype(dtype, copy=False)._ndarray
  File "/[working dir]/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 694, in astype
    raise TypeError(
TypeError: Casting to unit-less dtype 'datetime64' is not supported. Pass e.g. 'datetime64[ns]' instead.
```

**Comment by pedrotokar** [comment]
For what I've tested, changing line 21 of file`/pysocviz/loader/loader.py`  from
```py
    'Date': lambda x: x.astype('datetime64'),
```
to
```py
    'Date': lambda x: x.astype('datetime64[ns]'),
```
solves the probkem, but I don't know if this is a good fix or if it affects other thing
s, tho.

**Comment by Gedevan-Aleksizde** [comment]
Sorry for delayed much. Now I updated this package and fix many bugs including what you mentioned.

**Comment by pedrotokar** [comment]
Okay! Ty!
